"use client";

import { useMediaQuery } from "@material-ui/core";
import { NavBar } from "./components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isDesktop = useMediaQuery("(min-width:600px)");
  return (
    <html lang="en">
      <head>
        <title>Phat&apos;s Portfolio</title>
      </head>
      <body className={inter.className}>
        <NavBar isDesktop={isDesktop} />
        {children}
      </body>
    </html>
  );
}
