import { NavBar } from "./components/NavBar";
import DashBoardLayout from "./components/layouts/DashboardLayout";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Phat's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Phat&apos;s Portfolio</title>
      </head>
      <body className={inter.className} style={{ backgroundColor: "white" }}>
        <DashBoardLayout>{children}</DashBoardLayout>
      </body>
    </html>
  );
}
